project_id = "ndsqyhwsjxlhxuylgdal"

[functions.agent-api]
verify_jwt = false

[functions.agent-openapi]
verify_jwt = false

[functions.mcp]
verify_jwt = false

[functions.promote-checkout]
verify_jwt = false


